# Generated by Django 3.2.8 on 2021-10-24 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='name')),
                ('birthday', models.DateField(verbose_name='birthday')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('graduated', models.BooleanField(default=False, verbose_name='graduated')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='name')),
                ('birthday', models.DateField(verbose_name='birthday')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('at_work', models.BooleanField(default=True, verbose_name='at work')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
